const planUsage = {
  INFLUENCER_PROFILE_ANALYSIS: "INFLUENCER_PROFILE_ANALYSIS",
  INFLUENCER_SELECTION: "INFLUENCER_SELECTION",
  CAMPAIGN_USAGE: "CAMPAIGN_USAGE",
  POST_ANALYSIS: "POST_ANALYSIS",
};

export default planUsage;
